// Command doccmds turns the shell blocks of a Markdown guide into a bash
// script, so CI runs the commands exactly as a reader copies them (#50).
//
//	go run ./lab/doccmds docs/quickstart.md > /tmp/quickstart.sh
//
// Every ```sh or ```bash block is a step, run in order in one shell, so a
// `cd` or a variable set in one block holds for the next. A step fails the
// script when any of its commands fails. HTML comments right after a block
// (blank lines between are allowed) tell CI more without showing up in the
// rendered page:
//
//	<!-- ci-expect: text -->  the step's output must contain text
//	<!-- ci-absent: text -->  the step's output must not contain text
//	<!-- ci-retry: 60 -->     re-run the step every 2s for up to 60s until it
//	                          succeeds and its expectations hold
//	<!-- ci-fails -->         the step must exit non-zero
//	<!-- ci-skip: reason -->  do not run the step (the reason is required)
//
// Retried and ci-fails steps run in a subshell: they are checks and must not
// change state the next step relies on. The script prints each step's
// output, and on a failure the step and the expectation that failed.
package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

// Step is one shell block and the directives that follow it.
type Step struct {
	Line   int // line of the opening fence, for messages
	Body   string
	Expect []string
	Absent []string
	Retry  int // seconds; 0 runs once
	Fails  bool
	Skip   string
}

// Parse reads a Markdown document and returns its shell steps.
func Parse(r io.Reader) ([]Step, error) {
	var (
		steps []Step
		cur   *Step
		body  []string
		inSh  bool
		inAny bool
		fence string
		after bool // directly after a shell block: comments attach to it
	)
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	n := 0
	for sc.Scan() {
		n++
		line := sc.Text()
		trim := strings.TrimSpace(line)
		if inAny {
			if strings.HasPrefix(trim, fence) && strings.Trim(trim, "`~") == "" {
				inAny = false
				if inSh {
					inSh = false
					cur.Body = strings.Join(body, "\n")
					steps = append(steps, *cur)
					after = true
				}
				continue
			}
			if inSh {
				body = append(body, line)
			}
			continue
		}
		if strings.HasPrefix(trim, "```") || strings.HasPrefix(trim, "~~~") {
			marker := trim[:3]
			i := 0
			for i < len(trim) && trim[i] == marker[0] {
				i++
			}
			fence = trim[:i]
			info := strings.Fields(trim[i:])
			inAny = true
			after = false
			if len(info) > 0 && (info[0] == "sh" || info[0] == "bash" || info[0] == "shell") {
				inSh = true
				cur = &Step{Line: n}
				body = nil
			}
			continue
		}
		if trim == "" {
			continue
		}
		if strings.HasPrefix(trim, "<!--") && strings.HasSuffix(trim, "-->") {
			text := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(trim, "<!--"), "-->"))
			if !strings.HasPrefix(text, "ci-") {
				continue
			}
			if !after {
				return nil, fmt.Errorf("line %d: %q is not directly after a shell block", n, trim)
			}
			if err := directive(&steps[len(steps)-1], text); err != nil {
				return nil, fmt.Errorf("line %d: %w", n, err)
			}
			continue
		}
		after = false
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if inAny {
		return nil, errors.New("unterminated code block")
	}
	return steps, nil
}

func directive(s *Step, text string) error {
	name, arg, _ := strings.Cut(text, ":")
	name, arg = strings.TrimSpace(name), strings.TrimSpace(arg)
	switch name {
	case "ci-expect":
		if arg == "" {
			return errors.New("ci-expect needs text")
		}
		s.Expect = append(s.Expect, arg)
	case "ci-absent":
		if arg == "" {
			return errors.New("ci-absent needs text")
		}
		s.Absent = append(s.Absent, arg)
	case "ci-retry":
		v, err := strconv.Atoi(arg)
		if err != nil || v <= 0 || v > 600 {
			return fmt.Errorf("ci-retry wants seconds in 1-600, got %q", arg)
		}
		s.Retry = v
	case "ci-fails":
		if arg != "" {
			return errors.New("ci-fails takes no argument")
		}
		s.Fails = true
	case "ci-skip":
		if arg == "" {
			return errors.New("ci-skip needs a reason")
		}
		s.Skip = arg
	default:
		return fmt.Errorf("unknown directive %q", name)
	}
	if s.Fails && s.Retry > 0 {
		return errors.New("ci-fails and ci-retry cannot be combined")
	}
	return nil
}

// quote returns s as a single-quoted shell word.
func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const header = `#!/bin/bash
# Generated by lab/doccmds from %s. Do not edit; edit the guide.
set -euo pipefail
# fd 3 is the real stderr: a step that exits runs the trap inside its own
# output redirection.
exec 3>&2
__doc_log=$(mktemp)
__doc_step=""
trap 'rc=$?; if [ "$rc" -ne 0 ]; then echo "---- %s: step $__doc_step failed (exit $rc) ----" >&3; cat "$__doc_log" >&3 || true; fi; rm -f "$__doc_log"' EXIT
__doc_check() {
	local want
	for want in "${__doc_expect[@]}"; do
		if ! grep -qF -- "$want" "$__doc_log"; then echo "expected output: $want" >&2; return 1; fi
	done
	for want in "${__doc_absent[@]}"; do
		if grep -qF -- "$want" "$__doc_log"; then echo "unexpected output: $want" >&2; return 1; fi
	done
}
`

// Script writes the bash script for steps. name is the guide's path.
func Script(w io.Writer, name string, steps []Step) error {
	var b strings.Builder
	fmt.Fprintf(&b, header, name, name)
	for i, s := range steps {
		id := fmt.Sprintf("%d (%s line %d)", i+1, name, s.Line)
		if s.Skip != "" {
			fmt.Fprintf(&b, "\necho %s\n", quote("==== step "+id+": skipped: "+s.Skip))
			continue
		}
		fmt.Fprintf(&b, "\n__doc_step_%d() {\n%s\n}\n", i+1, s.Body)
		fmt.Fprintf(&b, "__doc_step=%s\n", quote(id))
		fmt.Fprintf(&b, "echo %s\n", quote("==== step "+id))
		for _, l := range strings.Split(s.Body, "\n") {
			fmt.Fprintf(&b, "echo %s\n", quote("$ "+l))
		}
		b.WriteString("__doc_expect=(")
		for _, e := range s.Expect {
			b.WriteString(" " + quote(e))
		}
		b.WriteString(" )\n__doc_absent=(")
		for _, e := range s.Absent {
			b.WriteString(" " + quote(e))
		}
		b.WriteString(" )\n")
		switch {
		case s.Fails:
			fmt.Fprintf(&b, "if ( set -e; __doc_step_%d ) >\"$__doc_log\" 2>&1; then echo 'expected the step to fail' >&2; false; fi\n", i+1)
			b.WriteString("cat \"$__doc_log\"\n__doc_check\n")
		case s.Retry > 0:
			fmt.Fprintf(&b, "__doc_end=$((SECONDS + %d))\n", s.Retry)
			fmt.Fprintf(&b, "until ( set -e; __doc_step_%d ) >\"$__doc_log\" 2>&1 && __doc_check 2>/dev/null; do\n", i+1)
			b.WriteString("\tif [ \"$SECONDS\" -ge \"$__doc_end\" ]; then __doc_check || true; false; fi\n\tsleep 2\ndone\n")
			b.WriteString("cat \"$__doc_log\"\n")
		default:
			fmt.Fprintf(&b, "__doc_step_%d >\"$__doc_log\" 2>&1\n", i+1)
			b.WriteString("cat \"$__doc_log\"\n__doc_check\n")
		}
	}
	b.WriteString("\necho '==== all steps passed'\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: doccmds GUIDE.md")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	defer f.Close()
	steps, err := Parse(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", os.Args[1], err)
		os.Exit(1)
	}
	if len(steps) == 0 {
		fmt.Fprintf(os.Stderr, "%s: no shell blocks\n", os.Args[1])
		os.Exit(1)
	}
	if err := Script(os.Stdout, os.Args[1], steps); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
