package configedit

import (
	"bytes"
	"errors"
	"fmt"
	"net/netip"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/GrandArcher/Packeteer/internal/config"
)

// Wizard limits.
const (
	MaxWizardProviders = 32
	MaxWizardNeighbors = 16
	MaxWizardTargets   = 1000
)

// WizardInput is the first-run form. The generated config is always
// mode observe: it measures and recommends, and never announces.
// Turning inject on is a separate, explicit edit.
type WizardInput struct {
	ASN       uint32           `json:"asn"`
	RouterID  string           `json:"router_id"`
	Providers []WizardProvider `json:"providers"`
	// Neighbors are the edge routers' addresses for the learn-only iBGP
	// sessions (the RIB view). Empty leaves BGP off: ranking only.
	Neighbors []string `json:"neighbors"`
	// Targets are the prefixes to probe, each with a host that answers.
	Targets []WizardTarget `json:"targets"`
	// Storage turns on report history (sqlite in /var/lib/packeteer).
	Storage bool `json:"storage"`
	// HTTPListen is the ops server address (default 127.0.0.1:8080).
	HTTPListen string `json:"http_listen"`
}

// WizardProvider is one upstream.
type WizardProvider struct {
	Name     string `json:"name" yaml:"name"`
	SourceIP string `json:"source_ip" yaml:"source_ip"`
	NextHop  string `json:"next_hop" yaml:"next_hop"`
}

// WizardTarget is one probed prefix.
type WizardTarget struct {
	Prefix string `json:"prefix"`
	Host   string `json:"host"`
}

// Output shapes; field order is file order.
type wizNeighbor struct {
	Address string `yaml:"address"`
}

type wizBGP struct {
	Neighbors []wizNeighbor `yaml:"neighbors"`
}

type wizPlugin struct {
	Type   string `yaml:"type"`
	Config any    `yaml:"config,omitempty"`
}

type wizHTTP struct {
	Listen string `yaml:"listen"`
}

type wizThresholds struct {
	MinLossDeltaPct float64 `yaml:"min_loss_delta_pct"`
	MinRTTDeltaMs   float64 `yaml:"min_rtt_delta_ms"`
}

type wizAllowlist struct {
	Prefixes []string `yaml:"prefixes"`
}

type wizConfig struct {
	Mode               string           `yaml:"mode"`
	ASN                uint32           `yaml:"asn"`
	RouterID           string           `yaml:"router_id"`
	PacketeerCommunity string           `yaml:"packeteer_community,omitempty"`
	MaxImprovements    int              `yaml:"max_improvements"`
	HoldTime           string           `yaml:"hold_time"`
	Thresholds         wizThresholds    `yaml:"thresholds"`
	Providers          []WizardProvider `yaml:"providers"`
	Allowlist          wizAllowlist     `yaml:"allowlist"`
	BGP                *wizBGP          `yaml:"bgp,omitempty"`
	Sources            []wizPlugin      `yaml:"sources"`
	Scorer             wizPlugin        `yaml:"scorer"`
	Storage            *wizPlugin       `yaml:"storage,omitempty"`
	HTTP               wizHTTP          `yaml:"http"`
}

const wizardHeader = `# Generated by the Packeteer first-run wizard (#34).
# mode: observe measures and recommends; it never announces a route.
# Injection needs an explicit edit: mode inject, an allowlist, local_pref,
# an announcer, and bgp.neighbors. See docs/CONFIG.md "Inject checklist".
`

// Wizard renders an observe-mode config from the form and checks it with
// config.Parse, the loader the controller uses. The allowlist is empty:
// nothing may be injected until an operator lists prefixes.
func Wizard(in WizardInput) ([]byte, error) {
	var errs []error
	add := func(format string, a ...any) { errs = append(errs, fmt.Errorf(format, a...)) }
	if len(in.Providers) < 1 || len(in.Providers) > MaxWizardProviders {
		add("providers: 1 to %d are required", MaxWizardProviders)
	}
	if len(in.Neighbors) > MaxWizardNeighbors {
		add("neighbors: at most %d", MaxWizardNeighbors)
	}
	if len(in.Targets) < 1 || len(in.Targets) > MaxWizardTargets {
		add("targets: 1 to %d are required", MaxWizardTargets)
	}
	for i, p := range in.Providers {
		if strings.ContainsAny(p.Name, "\r\n") {
			add("providers[%d]: name must be one line", i)
		}
	}
	targets := make([]map[string]string, 0, len(in.Targets))
	for i, t := range in.Targets {
		p, err := netip.ParsePrefix(strings.TrimSpace(t.Prefix))
		if err != nil {
			add("targets[%d]: prefix %q is not a prefix", i, t.Prefix)
			continue
		}
		h, err := netip.ParseAddr(strings.TrimSpace(t.Host))
		if err != nil || !p.Contains(h) {
			add("targets[%d]: host %q must be an address inside %s", i, t.Host, p)
			continue
		}
		targets = append(targets, map[string]string{"prefix": p.Masked().String(), "host": h.String()})
	}
	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	out := wizConfig{
		Mode: config.ModeObserve, ASN: in.ASN, RouterID: strings.TrimSpace(in.RouterID),
		MaxImprovements: config.DefaultMaxImprovements, HoldTime: "15m",
		Thresholds: wizThresholds{MinLossDeltaPct: 1, MinRTTDeltaMs: 15},
		Providers:  in.Providers,
		Allowlist:  wizAllowlist{Prefixes: []string{}},
		Sources:    []wizPlugin{{Type: "static", Config: map[string]any{"targets": targets}}},
		Scorer:     wizPlugin{Type: "weighted"},
		HTTP:       wizHTTP{Listen: config.DefaultHTTPListen},
	}
	if in.ASN > 0 && in.ASN <= 0xffff {
		out.PacketeerCommunity = strconv.FormatUint(uint64(in.ASN), 10) + ":666"
	}
	if len(in.Neighbors) > 0 {
		out.BGP = &wizBGP{}
		for _, n := range in.Neighbors {
			out.BGP.Neighbors = append(out.BGP.Neighbors, wizNeighbor{Address: strings.TrimSpace(n)})
		}
	}
	if in.Storage {
		out.Storage = &wizPlugin{Type: "sqlite", Config: map[string]string{"path": "/var/lib/packeteer/packeteer.db"}}
	}
	if l := strings.TrimSpace(in.HTTPListen); l != "" {
		out.HTTP.Listen = l
	}
	var b bytes.Buffer
	b.WriteString(wizardHeader)
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	cfg, err := config.Parse(b.Bytes())
	if err != nil {
		return nil, err
	}
	if cfg.Mode != config.ModeObserve {
		return nil, errors.New("wizard: generated config is not observe")
	}
	return b.Bytes(), nil
}
