package main

import (
	"fmt"
	"strings"
)

// Ports on the host network. The container and the harness share it.
type ports struct {
	BGP  int // the harness's router; Packeteer connects to it
	Flow int // Packeteer's IPFIX collector
	HTTP int // Packeteer's ops API
}

// packeteerConfig is the config the stock image runs with: observe, a
// learn-only iBGP session to the harness's router, the flow source, many
// static targets, and the fixed prober (no packets leave the host).
// transit-b is faster, so roughly half the measured prefixes have a
// recommendation, and observe announces none of them.
func packeteerConfig(p Profile, pt ports, dataDir string) string {
	tbl := newTable(p.Prefixes)
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by lab/soak for the load and soak test (#51). Lab only:
# documentation prefixes and ASNs, observe mode, no packets leave the host.
mode: observe
asn: %d
router_id: 192.0.2.10
packeteer_community: "64512:666"
max_improvements: 50
hold_time: 15m
thresholds:
  min_loss_delta_pct: 1.0
  min_rtt_delta_ms: 15
providers:
  - {name: transit-a, source_ip: 192.0.2.11, next_hop: %s}
  - {name: transit-b, source_ip: 192.0.2.12, next_hop: %s}
  - {name: transit-a6, source_ip: "2001:db8:ffff::11", next_hop: "%s"}
  - {name: transit-b6, source_ip: "2001:db8:ffff::12", next_hop: "%s"}
allowlist:
  prefixes: []
bgp:
  neighbors:
    - address: %s
      port: %d
      local_address: %s
      description: soak-router
probe:
  interval: 30s
  timeout: 1s
  packets: 4
  workers: 8
  rate_limit_pps: %d
probers:
  - type: fixed
    config:
      paths:
        - {provider: transit-a, rtt_ms: 40}
        - {provider: transit-b, rtt_ms: 10}
        - {provider: transit-a6, rtt_ms: 40}
        - {provider: transit-b6, rtt_ms: 10}
log:
  level: info
  format: text
http:
  listen: "127.0.0.1:%d"
storage:
  type: sqlite
  config:
    path: %s/packeteer.db
sources:
  - type: flow
    config:
      listen: "127.0.0.1:%d"
      window: 5m
      top_n: %d
`, labASN, nextHopsV4[0], nextHopsV4[1], nextHopsV6[0], nextHopsV6[1],
		routerAddr, pt.BGP, peerAddr, rateLimit(p), pt.HTTP, strings.TrimRight(dataDir, "/"), pt.Flow, max(1, p.FlowTopN))
	if p.StaticTargets > 0 {
		b.WriteString("  - type: static\n    config:\n      targets:\n")
		for k := range p.StaticTargets {
			i := k * (p.Prefixes / p.StaticTargets)
			fmt.Fprintf(&b, "        - {prefix: \"%s\", host: \"%s\"}\n", tbl.prefix(i), tbl.host(i))
		}
	}
	return b.String()
}

// rateLimit is the generated probe.rate_limit_pps. The pr and soak
// profiles leave it unset and keep 100000 so the fixed prober is not
// what bounds the run. The rate profile sets 100, the operator default.
func rateLimit(p Profile) int {
	if p.RateLimitPPS > 0 {
		return p.RateLimitPPS
	}
	return 100000
}
